// export {default as CreateItem} from './CreateItem';
// export {default as CreateMachineComponent} from './CreateMachineComponent';
// export {default as CreateSalaryComponent} from './CreateSalaryComponent';
// export {default as FooterComponent} from './FooterComponent';
// export {default as HeaderComponent} from './HeaderComponent';
// export {default as Invoice} from './InvoiceComponent';
//export {default as InvoiceTableComponent} from './InvoiceTableComponent';
// export {default as ListItemComponent} from './ListItemComponent';
// export {default as ListMachineComponent} from './ListMachineComponent';
// export {default as ListSalaryComponent} from './ListSalaryComponent';
// export {default as MachineryRentHome} from './MachineryRentHome';
// export {default as StatsBar} from './StatsBarComponent';
// export {default as SubNavBarComponent} from './SubNavBarComponent';
// export {default as UpdateItemComponent} from './UpdateItemComponent';
// export {default as UpdateMachineComponent} from './UpdateMachineComponent';
// export {default as UpdateSalaryComponent} from './UpdateSalaryComponent';
export {default as MyTheme} from './MyTheme';
